### PR TITLE
Rewrite the bookmarklet to use cssbeautify and Prism

### PR DESCRIPTION
**Pull request by sindresorhus**
Inlined both to make the bookmarklet fast.

Used cssbeautify instead since it's more tolerant for edge cases and actively maintained.

Screen Shot 2013-03-14 at 19 58 40

### CODE REVIEW

**Comment by sindresorhus** [comment]
I also created this https://github.com/sindresorhus/cssprettifier-userscript

Maybe we should do a linkshare?

**Comment by addyosmani** [comment]
Happy to do linkshare or shared project (Taste? org?). Whatever you're happy with.

Thanks so much for taking the time out to make these additions, man. I really appreciate it.

**Comment by sindresorhus** [comment]
I don't think tastejs org is a good fit for these, but I'll do a link back to this from the userscript ;)

**Comment by addyosmani** [comment]
SGTM :) I've revised the readme and added animated GIFs. Maybe release next week!

**Pull request merged**
